name: Linux Post Commit Checks

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - sycl
jobs:
   check:
   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v2
   - name: Test Backend
     shell: cd backend && make test
   - name: Update Images
     if: ${{ github.event_name == 'push' }}
     #     shell: make push
     shell: echo "TODO push docker images"

